/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab10;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static lab10.DifficultyEnum.EASY;
import static lab10.DifficultyEnum.HARD;
import static lab10.DifficultyEnum.MEDIUM;

/**
 *
 * @author Gehad
 */
public class SudokuGUI extends javax.swing.JFrame {

    /**
     * Creates new form SudokuGUI
     */
    public SudokuGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Load Game");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Generate Board");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel2.setText("==Sudoku Game Menu==");

        jButton3.setText("Continue");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(51, 51, 51)
                .addComponent(jButton3)
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addGap(40, 40, 40)
                .addComponent(jButton2)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new DifficultySelection().setVisible(true);
this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                                 
    GameStorage storage = new GameStorage();
    SudokuBoard currentBoard = null;

    try {
        // 1️⃣ Check if there is an unfinished game
        currentBoard = storage.loadCurrentGame();

        if (currentBoard != null && currentBoard.hasEmptyCells()) {
            // There is an unfinished game, ask if user wants to continue
            int choice = JOptionPane.showConfirmDialog(
                    this,
                    "You have an unfinished game. Do you want to continue?",
                    "Continue Game",
                    JOptionPane.YES_NO_OPTION
            );

            if (choice == JOptionPane.YES_OPTION) {
                // Load the unfinished game
                Board gameBoard = new Board(currentBoard);
                gameBoard.setVisible(true);
                this.dispose();
                return;
            }
        }

        // 2️⃣ No unfinished game, ask user to select difficulty
        String[] options = {"EASY", "MEDIUM", "HARD"};
        String selected = (String) JOptionPane.showInputDialog(
                this,
                "Select difficulty:",
                "Choose Difficulty",
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]
        );

        if (selected == null) return; // User cancelled
        DifficultyEnum difficulty = DifficultyEnum.valueOf(selected);

        // 3️⃣ Ask user to select a solved CSV
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select Solved Sudoku CSV File");
        int result = fileChooser.showOpenDialog(this);
        if (result != JFileChooser.APPROVE_OPTION) return;

        String path = fileChooser.getSelectedFile().getAbsolutePath();

        // 4️⃣ Generate boards
        GameDriver driver = new GameDriver(path);

        // Ensure folders exist
        Files.createDirectories(Paths.get("easy"));
        Files.createDirectories(Paths.get("medium"));
        Files.createDirectories(Paths.get("hard"));
        Files.createDirectories(Paths.get("incomplete"));

        DifficultyBoards boards = driver.generateDifficultyBoards();

        // 5️⃣ Save all boards
        storage.saveBoard(new SudokuBoard(boards.getEasy()), DifficultyEnum.EASY);
        storage.saveBoard(new SudokuBoard(boards.getMedium()), DifficultyEnum.MEDIUM);
        storage.saveBoard(new SudokuBoard(boards.getHard()), DifficultyEnum.HARD);

        // 6️⃣ Save the currently played board
        switch (difficulty) {
            case EASY -> currentBoard = new SudokuBoard(boards.getEasy());
            case MEDIUM -> currentBoard = new SudokuBoard(boards.getMedium());
            case HARD -> currentBoard = new SudokuBoard(boards.getHard());
        }
        storage.saveCurrentGame(currentBoard);

        // 7️⃣ Open the Board JFrame
        Board gameBoard = new Board(currentBoard);
        gameBoard.setVisible(true);
        this.dispose();

    } catch (InvalidSudokuException | IOException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }




    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      SudokuBoard board = null;
try {
    GameStorage storage = new GameStorage();
    board = storage.loadCurrentGame();
} catch (IOException ex) {
    Logger.getLogger(SudokuGUI.class.getName()).log(Level.SEVERE, null, ex);
}

if (board == null) {
    JOptionPane.showMessageDialog(this, "No unfinished game found.");
    return; // stop further execution
}

// Open the board
new Board(board).setVisible(true);
this.dispose();


    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SudokuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SudokuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SudokuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SudokuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SudokuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
